apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-go-hw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-go-hw
  template:
    metadata:
      labels:
        app: aks-go-hw
    spec:
      containers:
      - name: aks-go-hw
        image: emersonregistry.azurecr.io/go-hw:v1
        ports:
        - containerPort: 3000
        env:
        - name: TITLE
          value: "AKS Ingress Demo"
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: aks-go-hw
spec:
  type: ClusterIP
  ports:
  - port: 3000
  selector:
    app: aks-go-hw